version: '3.1'

services:
  adminer:
    #image: adminer/latest
    build: .
    networks:
      - "${AD_NW}"
    ports:
      - "${AD_PORT}:8888"

# SPDX-License-Identifier: (EUPL-1.2)
# Copyright © 2019-2020 Simon Prast
